baseURL: "https://lecturestudio.org/"
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
disableDefaultLanguageRedirect: true
languageCode: "en-GB"
title: "lectureStudio"

# SEO Configuration
enableRobotsTXT: true
