main:
  - name: Dokumentation
    pageRef: /documentation
    weight: 10
  - name: Download
    pageRef: /download
    weight: 20
  - name: Tutorials
    pageRef: /tutorials
    weight: 30
  - name: FAQ
    pageRef: /faq
    weight: 40
  - name: Sponsoren
    pageRef: /sponsors
    weight: 50
  - name: Kontakt
    pageRef: /contact
    weight: 60

footer:
  - name: Impressum
    pageRef: https://www.informatik.tu-darmstadt.de/impressum.de.jsp
    weight: 10
  - name: Datenschutzerklärung
    pageRef: https://www.tu-darmstadt.de/datenschutzerklaerung.de.jsp
    weight: 20
  - name: Kontakt
    pageRef: /contact
    weight: 30